### PR TITLE
Slight changes on the design part

### PR DESCRIPTION
**Pull request by 3lna7**
I used both bootstrap and CSS to touch up the overall outcome. The search part was a bit hard to really make changes to so I left it alone.
Also, I checked the write review before and after the changes and I was not sure how the write review is working in our system now. Please let me know if you are able to write a review and I check again before merging.

### CODE REVIEW

**Review by bumkyu00 — CHANGES_REQUESTED** [review]
다 괜찮은데, 테스트도 같이 바꿔야 할 것 같아요. 예를 들어 menuBar.test.js에서는 button class를 찾는 대신 Button으로 바꿔야 할 것 같네요.

**Comment by 3lna7** [comment]
I could find those missing in the test cases. Please let me know if I again missed some parts. Thank you

**Comment by 3lna7** [comment]
Should I merge it now?

**Comment by bumkyu00** [comment]
Yeah I think it's good

**Comment by 3lna7** [comment]
Let me know if it need changes

**Pull request merged**
